// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsUubZgbBJ3gZqQYYy36Pab7gUytsEEg4',
    appId: '1:374463156240:android:011146410a00f764303a95',
    messagingSenderId: '374463156240',
    projectId: 'craftybay-ecommerce-project',
    storageBucket: 'craftybay-ecommerce-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW1H6wK8J_zxzaT-_j4U6Q32mXJpN8EXA',
    appId: '1:374463156240:ios:a041df227f8981fe303a95',
    messagingSenderId: '374463156240',
    projectId: 'craftybay-ecommerce-project',
    storageBucket: 'craftybay-ecommerce-project.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAy1zSC3D3AK70bMZbFEJw6Wui1k-0zyyw',
    appId: '1:374463156240:web:e8cc44412dc6446d303a95',
    messagingSenderId: '374463156240',
    projectId: 'craftybay-ecommerce-project',
    authDomain: 'craftybay-ecommerce-project.firebaseapp.com',
    storageBucket: 'craftybay-ecommerce-project.firebasestorage.app',
    measurementId: 'G-XZJ1Y2XT1R',
  );
}
